### ISSUE TITLE
Events should have an "all day" option

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/sandcal#10]
I found it really odd when making my test event for my birthday that I had to set a time. I often add notes about particular days, and calendars generally support marking something as an all day event.

**Comment by zenhack** [comment]
Yeah, this is another case of "need to add a UI." FWIW it does correctly label imported all-day events.

**Comment by ocdtrekkie** [comment]
I figured as much. I just figure the first things I hit are the same things others will wonder about.

(Also, and this is really a #8 thing, I tried seeing if not setting a date would give me an all day event, and it did the blank page thing.)
