### ISSUE TITLE
Delete & modify events

### ISSUE THREAD

**Issue by zenhack** [zenhack/sandcal#2]
We should provide a way to delete and/or modify existing events.

Delete should have the options of deleting only a given occurrence, all events, or all future events.

**Comment by zenhack** [comment]
Status on this: this is mostly implemented, but:

- The edit doesn't handle every possible representable icalendar event gracefully, so for some ics imports you'll get errors from the server when saving, and some important information is sometimes missing from the UI when editing. It's fine for events created through the UI though.
- I haven't implemented the ability to delete only one occurrence; the delete is all or nothing.

**Comment by ocdtrekkie** [comment]
What is the gap between "every representable iCalendar event" and "events created through the UI"? Is iCal endlessly complex, or is this going to be "good enough"?

**Comment by zenhack** [comment]
So, the bad things that happen now that we should probably avoid:

- If the repeat rules are more complex than what shows up in the UI, you get the closest thing that's representable -- so if you have an event that happens on e.g. the 2nd saturday of every month, it'll just show up as "monthly" and when you save it it will just end up being day N of the month, where N is whatever day of the month the second saturday was in the month you were looking at.
- If the event spans multiple days, we just ignore the date part of the end time.
- There are some cases where the code can't work out what to use for the start/end date -- I think with iCalendar it's possible to encode things like "every thursday, from the big bang until the end of time" (by just leaving out the start/end dates), and SandCal is unhappy if it can't come up with a start date. In this case you'll just get a 500 from the server.

There are some related problems with displaying events: we don't currently understand all of the recurrence rule types there either, so some repeating events will not occur in all the right spots.

At some point I want SandCal to be able to deal with most stuff found in the wild, and the bits that are complex are also for the most part useful -- the iCalendar format isn't much more gnarly than the way people work with dates & times (i.e. it's not the format's fault). But this might have to be best effort for the short term.

The good news is that if you import an ics file, we store it as-is, so as the software improves the interpretation will get better; no need to hold off on uploading stuff for fear of it being mangled. But the right approach may be to just mark the ics import support as "alpha" for a little while.

**Comment by zenhack** [comment]
So, here's what I think I'm going to do:

- Open a separate issue about deleting single-occurrences, and close this (as everything else here is done).
- Add a notice to the ics import that it's alpha-quality.
- Add some csrf checking; this has been in the back of my head as something I need to do before a release, but I guess I never opened an issue about it.
- Call this good for a first release (though I guess I need an icon...). We've got jankier stuff in the app market.
