### ISSUE TITLE
When editing an existing all-day event, the all-day checkbox is not preselected

### ISSUE THREAD

**Issue by timmc** [zenhack/sandcal#26]
1. Create an all-day event
2. Click "Edit" link

- Expected: "All Day" is checked
- Actual: Not checked

However, I think this is just cosmetic; leaving the box unchecked doesn't seem to change the scheduling at all.

**Comment by zenhack** [comment]
Good catch. Fixed, new spk is pending approval (cc @ocdtrekkie)
