### ISSUE TITLE
Input boxes force zoom on iOS

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/sandcal#29]
If we can get the same fix as your other projects on the new event form, example here: https://github.com/zenhack/yata/commit/7a8815c79fa4b7b1d657c9ab05d7c0d4566989a8

**Comment by zenhack** [comment]
Huh, I'm surprised we didn't hit this with sandcal already.

...I should probably start maintaining a baseline stylesheet for new projects, so I don't introduce this bug in *every* app I write...
