### ISSUE TITLE
Display useful information on the per-event page.

### ISSUE THREAD

**Issue by zenhack** [zenhack/sandcal#3]
Right now the page for viewing a single event just has a heading with the event name; we should flesh this out, providing more useful information.

**Comment by ocdtrekkie** [comment]
At minimum, a description field, a participants field (which should eventually be able to send invites), and a location field would be nice. If the location field contains a URL, we definitely want to make it clickable and have it open in a new tab.

**Comment by zenhack** [comment]
Pushed a few changes. Now the event page also displays the time of the event, along with the fields you suggested if present. (though note that the UI doesn't provide a way to enter these, so they will only be there if they were imported).

**Comment by zenhack** [comment]
Now also displays info about recurring events. I'm going to close this one; there may be further changes to make, but the basic "it's a blank screen" is solved; we can open separate issues for specific items.
