### ISSUE TITLE
ICS export

### ISSUE THREAD

**Issue by zenhack** [zenhack/sandcal#6]
We should provide the ability to export a calendar as an .ics file. We already provide import.

This should be pretty easy to add.

**Comment by ocdtrekkie** [comment]
Ideally, this should also be available at an API endpoint. My mail client lets me subscribe to URLs with ICS output and regularly checks for updates to display.

**Comment by zenhack** [comment]
Yeah, that should be fairly easy to do.

**Comment by zenhack** [comment]
Basic version of this is implemented, but I'm going to leave this open until we also provide an offer-iframe/api endpoint. Before we do that though we need to add a read-only permission mode.
