### ISSUE TITLE
Upcoming events view needs some limits for recurring events

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/sandcal#9]
I added a yearly recurring event (my birthday!) to my test grain, and the Upcoming Events page now has that going all the way out to the year 2119. That feels a little excessive to display at once. I don't think anything over a year out should ever be considered an "upcoming event" on a calendar app.

**Comment by zenhack** [comment]
Yeah, right now it's capped to 100 events, but (1) possibly that's too many and (2) there probably should be some time-based horizon too.

**Comment by zenhack** [comment]
Added some more reasonable limits; closing.
